name: Build (Tagged Releases)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: make -j

      - name: Test
        shell: bash
        run: make test
